Update models
PTIT-D22KH/milktea_sales_management_project pull request #3
Opened 2024-09-27 03:35 UTC by TINABJan254

Add Employee.java and FoodCategory.java to models

2024-09-27 04:53 UTC, duongvu5 requested changes
Tôi đang tính đổi 1 số chỗ nhỏ nên ông đợi nhé

2024-09-27 05:49 UTC, nhatzonz approved these changes

2024-09-27 13:36 UTC, duongvu5 approved these changes
okay, đã sửa tên thuộc tính

2024-09-27 15:39 UTC, duongvu5 commented
@BuiVannn  @PearPn15

2024-09-28 12:15 UTC, BuiVannn approved these changes
Ok

2024-09-29 06:39 UTC, PearPn15 approved these changes

2024-09-29 06:39 UTC, PearPn15 approved these changes

2024-09-29 06:39 UTC, merged